server:
  port: 8880

test:
  hello: Hello3

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 7355608
    url: jdbc:mysql://127.0.0.1:3306/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root